version: '3.7'
services: 
    database:
        image: mysql:latest
        volumes:
            - ./covidcases.sql:/docker-entrypoint-initdb.d/covidcases.sql
            - /var/lib/mysql
        ports:
            - "33061:3306"
        environment:
            - MYSQL_USER=slopeza
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=slopeza 
        restart: always 
        container_name: database
    jupyter:
        build: ./Jupyter
        environment: 
            - JUPYTER_TOKEN=root
        volumes: 
            - /app/
        ports: 
            - 8888:8888
        container_name: jupyter
        depends_on: 
            - database
        links: 
            - "database:db"
    dash:
        build: ./dash
        volumes: 
            - ./dash:/usr/src/app
        ports: 
            - 7070:70
        depends_on: 
            - database
        links: 
            - "database:db"

        
                